name: Build and push images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 11

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - run: cd client
      - run: npm install -g gulp@4.0.0 gulp-cli
      - run: yarn install
        working-directory: ./client
      - run: gulp
        working-directory: ./client
        env:
          DISABLE_LOGGING: 1
          NODE_ENV: production

      - run: go mod download
      - run: make alpine

      - run: pwd && ls -lah && find .
